remote_theme: pages-themes/cayman@v0.2.0
lsi: false
safe: true
source: content
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

