title: Protecting the Pages
description: A visualization of contemporary book banning
author: abigailcorcelli
lang: en-US
url: "https://abigailcorcelli.github.io" # Update with your GitHub username
baseurl: "/abigailcorcelli.github.io" # Update with your repository name if hosted in a subdirectory

theme: null # Remove any reference to remote themes since you're using a custom layout

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

plugins:
  - jekyll-feed

sass:
  sass_dir: _sass
  style: compressed
