remote_theme: pages-themes/cayman@v0.2.0
lsi: false
safe: true
source: abigailcorcelli.github.io
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed

