title: Protecting the Pages
description: A visualization of contemporary book banning
author: abigailcorcelli
lang: en-US
url: "https://abigailcorcelli.github.io" 
baseurl: "/abigailcorcelli.github.io" 

theme: null 

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "_layouts/default.html"

plugins:
  - jekyll-feed

sass:
  sass_dir: _sass
  style: compressed
